# Generated by Django 3.1.13 on 2022-11-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('floors', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buildingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
            ],
        ),
    ]
