# Generated by Django 3.1.13 on 2022-11-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0002_floor_block'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='floors.floor'),
        ),
    ]
