# Generated by Django 3.1.13 on 2022-11-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='image',
        ),
    ]
