# Generated by Django 3.1.13 on 2022-11-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_remove_building_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='state',
        ),
    ]
