# Generated by Django 4.1.3 on 2022-11-05 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockB',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('floors', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buildingId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
            ],
        ),
    ]
