# Generated by Django 4.1.2 on 2022-11-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0008_rename_rooms_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="OfferGeo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("goal", models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Test",
        ),
        migrations.AddField(
            model_name="offer",
            name="geo",
            field=models.ManyToManyField(
                related_name="offers", to="buildings.offergeo"
            ),
        ),
    ]
