# Generated by Django 4.1.2 on 2022-11-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0010_remove_item_room_item_items_delete_offer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="items",
        ),
        migrations.AddField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    (
                        "Electrical",
                        (
                            ("Fan", "Fan"),
                            ("TubeLight", "TubeLight"),
                            ("Bulb", "Bulb"),
                            ("Other", "Other"),
                        ),
                    ),
                    (
                        "Plumbing",
                        (
                            ("Flush", "Flush"),
                            ("Tank", "Tank"),
                            ("Taps", "Taps"),
                            ("Other", "Other"),
                        ),
                    ),
                    (
                        "Furniture",
                        (("Chair", "Chair"), ("Table", "Table"), ("Other", "Other")),
                    ),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="buildings.room",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Office", "Office"),
                    ("Lab", "Lab"),
                    (
                        "Ward",
                        (
                            ("Multibed Ward", "Multibed Ward"),
                            ("Single Bed Ward", "Single Bed Ward"),
                            ("Twin Sharing Room", "Twin Sharing Room"),
                            ("Single Room", "Single Room"),
                            ("Single Deluxe Room", "Single Deluxe Room"),
                            ("Super Deluxe Room", "Super Deluxe Room"),
                            ("Suite", "Suite"),
                        ),
                    ),
                    ("Store", "Store"),
                    ("Other", "Other"),
                ],
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="RoomItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buildings.item"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="buildings.room"
                    ),
                ),
            ],
        ),
    ]
