# Generated by Django 4.1.2 on 2022-11-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0011_remove_item_items_item_item_type_item_room_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="room",
        ),
        migrations.AddField(
            model_name="room",
            name="items",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_items",
                through="buildings.RoomItem",
                to="buildings.item",
            ),
        ),
    ]
