# Generated by Django 3.1.13 on 2022-11-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.block'),
        ),
    ]
